Analysis
EnergyAnalysis Model
Demonstrates how to use EnergyAnalysisModel API.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\EnergyAnalysisModel\CS\bin\Debug\net8.0-windows\EnergyAnalysisModel.dll
Revit.SDK.Samples.EnergyAnalysisModel.CS.Command

Annotation
Tag Rooms
Auto tag all rooms in a specified level.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AutoTagRooms\CS\bin\Debug\net8.0-windows\AutoTagRooms.dll
Revit.SDK.Samples.AutoTagRooms.CS.Command

Annotation
ColorFill Scheme and Legend creation and modification.
This sample demonstrates how to create ColorFill scheme, add entries and modify entries for colorFill scheme. It also demonstrates how to create colorFill legend with scheme and modify its appearance.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ColorFill\CS\bin\Debug\net8.0-windows\ColorFill.dll
Revit.SDK.Samples.ColorFill.CS.Command

Annotation
Create Dimensions
Add a dimension to a selected structural wall from its start to its end. Name the dimensions 'Dimension N' where N is an increasing number for each dimension.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateDimensions\CS\bin\Debug\net8.0-windows\CreateDimensions.dll
Revit.SDK.Samples.CreateDimensions.CS.Command

Annotation
LeaderLineAndDimensionLineSuperposition.
Using new dimension api to move leader end point. Make the dimension line and leader line to be superposition. 
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DimensionLeaderEnd\CS\bin\Debug\net8.0-windows\DimensionLeaderEnd.dll
Revit.SDK.Samples.DimensionLeaderEnd.CS.MoveHorizontally

Annotation
MoveToPickedPoint.
Using new dimension api to move leader end point. Move to picked point. 
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DimensionLeaderEnd\CS\bin\Debug\net8.0-windows\DimensionLeaderEnd.dll
Revit.SDK.Samples.DimensionLeaderEnd.CS.MoveToPickedPoint

Annotation
Spot Dimension
Get all spot dimensions in all views and show their properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SpotDimension\CS\bin\Debug\net8.0-windows\SpotDimension.dll
Revit.SDK.Samples.SpotDimension.CS.Command

Annotation
TagBeam - Tag Beam
Tag beam's start and end.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TagBeam\CS\bin\Debug\net8.0-windows\TagBeam.dll
Revit.SDK.Samples.TagBeam.CS.Command

Annotation
TagBeam - Tag Rebar
Tag selected Rebar.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TagBeam\CS\bin\Debug\net8.0-windows\TagBeam.dll
Revit.SDK.Samples.TagBeam.CS.TagRebar

Annotation
TagBeam - Create Text
Create a new TextNote instance for selected Rebar.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TagBeam\CS\bin\Debug\net8.0-windows\TagBeam.dll
Revit.SDK.Samples.TagBeam.CS.CreateText

Annotation, Basics
Capitalize all TextNote elements
This command iterates through the document and applies the 'AllCaps' formatting to them.  This will show text in upper case characters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CapitalizeAllTextNotes\CS\bin\Debug\net8.0-windows\CapitalizeAllTextNotes.dll
Revit.SDK.Samples.CapitalizeAllTextNotes.CS.Command

Annotation, Basics
Delete Dimensions
Delete all unpinned dimensions found in current selection.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DeleteDimensions\CS\bin\Debug\net8.0-windows\DeleteDimensions.dll
Revit.SDK.Samples.DeleteDimensions.CS.Command

Annotation, Basics
In-Canvas controls
This sample will demonstrate how to create, keep track of and handle clicks on In-Canvas controls.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\InCanvasControlAPI\CS\bin\Debug\net8.0-windows\InCanvasControlAPI.dll
Revit.SDK.Samples.InCanvasControlAPI.CS.Command

Annotation, Elements
Infrastructure alignments
Demonstrates the use of API for finding and labeling an infrastructure alignment element.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CivilAlignments\CS\bin\Debug\net8.0-windows\CivilAlignments.dll
Revit.SDK.Samples.CivilAlignments.CS.CreateAlignmentStationLabelsCmd

Annotation, Elements
Infrastructure alignments with labels
Demonstrates the use of API for listing properties of an infrastructure alignment element and its labels.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CivilAlignments\CS\bin\Debug\net8.0-windows\CivilAlignments.dll
Revit.SDK.Samples.CivilAlignments.CS.ShowPropertiesCmd

Annotation, Elements, Views
Create PathOfTravel.
This sample demonstrated how to create PathOfTravel elements from room(s) to door(s) in a plan view.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PathOfTravel\CS\bin\Debug\net8.0-windows\PathOfTravel.dll
Revit.SDK.Samples.PathOfTravelCreation.CS.Command

Basics
Delete Objects (CS)
Delete selected elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DeleteObject\CS\bin\x64\Debug\net8.0-windows\DeleteObject.dll
Revit.SDK.Samples.DeleteObject.CS.Command

Basics
ErrorHandling
Demonstrates how to use the error handling framework..
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ErrorHandling\CS\bin\Debug\net8.0-windows\ErrorHandling.dll
Revit.SDK.Samples.ErrorHandling.CS.Command

Basics
ProgressNotifier
ProgressNotifier
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Events\ProgressNotifier\CS\bin\x64\Debug\net8.0-windows\ProgressNotifier.dll
Revit.SDK.Samples.ProgressNotifier.CS.Command

Basics
Hello Revit (CS)
Shows how a basic ExternalCommand can be added to the Revit user interface.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\HelloRevit\CS\bin\Debug\net8.0-windows\HelloRevit.dll
Revit.SDK.Samples.HelloRevit.CS.Command

Basics
Journaling
Show how an external application can participate in the journaling mechanism.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Journaling\CS\bin\Debug\net8.0-windows\Journaling.dll
Revit.SDK.Samples.Journaling.CS.Command

Basics
Show Modeless Form (External Event)
This sample shows how to utilize an External Event object  in order to communicate with the Revit API from an external  modeless dialog.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ModelessDialog\ModelessForm_ExternalEvent\CS\bin\Debug\net8.0-windows\ModelessForm_ExternalEvent.dll
Revit.SDK.Samples.ModelessForm_ExternalEvent.CS.Command

Basics
Show Modeless Form (Idling Event)
An applicaiton with a modeless dialog using the Idling event to comunicate with Revit API
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ModelessDialog\ModelessForm_IdlingEvent\CS\bin\Debug\net8.0-windows\ModelessForm_IdlingEvent.dll
Revit.SDK.Samples.ModelessForm_IdlingEvent.CS.Command

Basics
Analyze Wall Face
This sample shows how to utilize the Applicaiton.Idling event in order to communicate with the Revit API from an external work thread.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MultiThreading\WorkThread\CS\bin\Debug\net8.0-windows\WorkThread.dll
Revit.SDK.Samples.WorkThread.CS.Command

Basics
Highlight by Phase
Highlight by Phase.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PhaseSample\VB.NET\bin\x64\Debug\net8.0-windows\PhaseSample.dll
Revit.SDK.Samples.PhaseSample.VB.NET.Command

Basics
Project Information
Project Information.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ProjectInfo\CS\bin\Debug\net8.0-windows\ProjectInfo.dll
Revit.SDK.Samples.ProjectInfo.CS.Command

Basics
TransactionControl
Demonstrate how to use transaction control.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TransactionControl\CS\bin\Debug\net8.0-windows\TransactionControl.dll
Revit.SDK.Samples.TransactionControl.CS.Command

Basics, Data Exchange
Units API
The sample of Revit Units API.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Units\CS\bin\Debug\net8.0-windows\Units.dll
Revit.SDK.Samples.Units.CS.Command

Basics, Elements
Display Options
Display Options.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DesignOptionReader\VB.NET\bin\x64\Debug\net8.0-windows\DesignOptionReader.dll
Revit.SDK.Samples.DesignOptionReader.VB.NET.Command

Basics, Families
Interactive placement of family instance via options
This sample demonstrates how to place the family instance via options
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PlacementOptions\CS\bin\Debug\net8.0-windows\PlacementOptions.dll
Revit.SDK.Samples.PlacementOptions.CS.Command

Basics, Families
RvtCmd_LibraryPaths
List the Revit library paths.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\x64\Debug\net8.0-windows\RevitCommands.dll
Revit.SDK.Samples.RevitCommands.VB.NET.RvtCmd_LibraryPaths

Basics, Families
RvtCmd_LoadFamilySymbol
Load a family symbol/type.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\x64\Debug\net8.0-windows\RevitCommands.dll
Revit.SDK.Samples.RevitCommands.VB.NET.RvtCmd_LoadFamilySymbol

Basics, Families
RvtCmd_LoadFamily
Load a family.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\x64\Debug\net8.0-windows\RevitCommands.dll
Revit.SDK.Samples.RevitCommands.VB.NET.RvtCmd_LoadFamily

Basics, Families
RvtCmd_Selection
show how to use selection set.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\x64\Debug\net8.0-windows\RevitCommands.dll
Revit.SDK.Samples.RevitCommands.VB.NET.RvtCmd_Selection

Basics, Families
RvtCmd_ShowElementData
show parameters in selected entities.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RevitCommands\VB.NET\bin\x64\Debug\net8.0-windows\RevitCommands.dll
Revit.SDK.Samples.RevitCommands.VB.NET.RvtCmd_ShowElementData

Basics, Geometry
Display graphics using DirectContext3D
Select elements whose graphics should be redrawn using DirectContext3D.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DuplicateGraphics\CS\bin\Debug\net8.0-windows\DuplicateGraphics.dll
Revit.SDK.Samples.DuplicateGraphics.CS.CommandDuplicateGraphics

Basics, Geometry
Clear DirectContext3D graphics
Remove external graphics.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DuplicateGraphics\CS\bin\Debug\net8.0-windows\DuplicateGraphics.dll
Revit.SDK.Samples.DuplicateGraphics.CS.CommandClearExternalGraphics

Basics, Geometry
ReferencePlane
Allow user to create a reference plane at the left face of the wall or at the bottom of slab which is selected first.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ReferencePlane\CS\bin\Debug\net8.0-windows\ReferencePlane.dll
Revit.SDK.Samples.ReferencePlane.CS.Command

Basics, Geometry, Views
Export 2D views with CustomExporter
Export 2D views with CustomExporter, using varying options of the exporter.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CustomExporter\Custom2DExporter\CS\bin\Debug\net8.0-windows\Custom2DExporter.dll
Revit.SDK.Samples.Custom2DExporter.CS.Command

Basics, Parameters
About Revit
Show the Revit product name, version and build number.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\VersionChecking\CS\bin\Debug\net8.0-windows\VersionChecking.dll
Revit.SDK.Samples.VersionChecking.CS.Command

Basics, Structure
Rotate Framing Objects (CS)
Rotate selected objects, such as beams, braces and columns.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RotateFramingObjects\CS\bin\Debug\net8.0-windows\RotateFramingObjects.dll
Revit.SDK.Samples.RotateFramingObjects.CS.RotateFramingObjects

Data Exchange
Arch Sample - Export to Excel
Export data to Excel, sorted by categories
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ArchSample\VB.NET\bin\x64\Debug\net8.0-windows\ArchSample.dll
Revit.SDK.Samples.ArchSample.VB.NET.Command

Data Exchange
Import and Export
Export current project to dwg, dwf(x), gbxml or fbx files and import a dwg or image file into Revit.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ImportExport\CS\bin\Debug\net8.0-windows\ImportExport.dll
Revit.SDK.Samples.ImportExport.CS.Command

Data Exchange
Panel Schedule Sample - Export Data
Exoport Revit Panle Schedule(s) to CSV file(s) or HTML page(s).
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PanelSchedule\CS\bin\Debug\net8.0-windows\PanelSchedule.dll
Revit.SDK.Samples.PanelSchedule.CS.PanelScheduleExport

Data Exchange
Panel Schedule Sample - View Instance Creation
Create Panel Schedule View instance for a panel.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PanelSchedule\CS\bin\Debug\net8.0-windows\PanelSchedule.dll
Revit.SDK.Samples.PanelSchedule.CS.InstanceViewCreation

Data Exchange
Panel Schedule Sample - Sheet Instance Creation
Place Panel Schedule View instance on a sheet view.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PanelSchedule\CS\bin\Debug\net8.0-windows\PanelSchedule.dll
Revit.SDK.Samples.PanelSchedule.CS.SheetImport

Data Exchange
View Printer
Print user selected printable views.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ViewPrinter\CS\bin\Debug\net8.0-windows\ViewPrinter.dll
Revit.SDK.Samples.ViewPrinter.CS.Command

Data Exchange, Families
DWGFamilyCreation
Import dwg file into family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\DWGFamilyCreation\CS\bin\Debug\net8.0-windows\DWGFamilyCreation.dll
Revit.SDK.Samples.DWGFamilyCreation.CS.Command

Elements
Create CompoundStructure for wall
This command is to create CompoundStructure for wall.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CompoundStructure\CS\bin\Debug\net8.0-windows\CompoundStructure.dll
Revit.SDK.Samples.CompoundStructureCreation.CS.WallCompoundStructure

Elements
Create and set FillPattern
Create and set FillPattern or LinePattern to face and grid
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateFillPattern\CS\bin\Debug\net8.0-windows\CreateFillPattern.dll
Revit.SDK.Samples.CreateFillPattern.CS.Command

Elements
Curtain System
Create curtain systems and edit their curtain grids
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CurtainSystem\CS\bin\Debug\net8.0-windows\CurtainSystem.dll
Revit.SDK.Samples.CurtainSystem.CS.Command

Elements
Curtain Wall and Grid
Create a curtain wall and edit its grid
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CurtainWallGrid\CS\bin\Debug\net8.0-windows\CurtainWallGrid.dll
Revit.SDK.Samples.CurtainWallGrid.CS.Command

Elements
Datumplane modification
Datumplane modification
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DatumsModification\CS\bin\Debug\net8.0-windows\DatumsModification.dll
Revit.SDK.Samples.DatumsModification.CS.Command

Elements
Create and modify view filters.
Create and modify view filters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ElementFilter\ViewFilters\CS\bin\Debug\net8.0-windows\ViewFilters.dll
Revit.SDK.Samples.ViewFilters.CS.Command

Elements
Extensible Storage Manager
Extensible Storage Manager
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ExtensibleStorageManager\ExtensibleStorageManager\CS\bin\x64\Debug\net8.0-windows\ExtensibleStorageManager.dll
ExtensibleStorageManager.Command

Elements
ExtensibleStorageUtility-DeleteStorage
ExtensibleStorageUtility-DeleteStorage
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ExtensibleStorageUtility\CS\bin\Debug\net8.0-windows\ExtensibleStorageUtility.dll
Revit.SDK.Samples.ExtensibleStorageUtility.CS.DeleteStorage

Elements
ExtensibleStorageUtility-QueryStorage
ExtensibleStorageUtility-QueryStorage
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ExtensibleStorageUtility\CS\bin\Debug\net8.0-windows\ExtensibleStorageUtility.dll
Revit.SDK.Samples.ExtensibleStorageUtility.CS.QueryStorage

Elements
Foundation Slab
Convert regular floors at the base of the building to octagonal slabs.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FoundationSlab\CS\bin\Debug\net8.0-windows\FoundationSlab.dll
Revit.SDK.Samples.FoundationSlab.CS.Command

Elements
GenerateFloor
Generate a floor using a selection of walls that make a closed outline.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GenerateFloor\CS\bin\Debug\net8.0-windows\GenerateFloor.dll
Revit.SDK.Samples.GenerateFloor.CS.Command

Elements
Grid Creation
Show how to create grids.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GridCreation\CS\bin\Debug\net8.0-windows\GridCreation.dll
Revit.SDK.Samples.GridCreation.CS.Command

Elements
Create levels
Show how to get all the levels in a document and how to create and delete a level and set its properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\LevelsProperty\CS\bin\Debug\net8.0-windows\LevelsProperty.dll
Revit.SDK.Samples.LevelsProperty.CS.Command

Elements
Model Lines
Report the number of each model line type and allow the user to specify the shape and sketch plane to create some new model lines.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ModelLines\CS\bin\Debug\net8.0-windows\ModelLines.dll
Revit.SDK.Samples.ModelLines.CS.Command

Elements
New hosted sweep
Create hosted sweep and modify created hosted sweep
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewHostedSweep\CS\bin\Debug\net8.0-windows\NewHostedSweep.dll
Revit.SDK.Samples.NewHostedSweep.CS.Command

Elements
New Openings
Create openings on the selected floor or wall.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewOpenings\CS\bin\Debug\net8.0-windows\NewOpenings.dll
Revit.SDK.Samples.NewOpenings.CS.Command

Elements
NewRoof
Create or edit footprint roof and extrusion roof.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewRoof\CS\bin\Debug\net8.0-windows\NewRoof.dll
Revit.SDK.Samples.NewRoof.CS.Command

Elements
Openings
Display openings in project, and create model lines along its edges.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Openings\CS\bin\Debug\net8.0-windows\Openings.dll
Revit.SDK.Samples.Openings.CS.Command

Elements
PerformanceAdviserControl
PerformanceAdviserControl
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PerformanceAdviserControl\CS\bin\Debug\net8.0-windows\PerformanceAdviserControl.dll
Revit.SDK.Samples.PerformanceAdviserControl.CS.UICommand

Elements
Shared Coordinate System
Display the locations and site information of the project.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SharedCoordinateSystem\CS\bin\Debug\net8.0-windows\SharedCoordinateSystem.dll
Revit.SDK.Samples.SharedCoordinateSystem.CS.Command

Elements
Stairs automation
A utility sample that creates a series of stairs, stairs runs and stairs landings configurations based upon predefined rules and parameters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\StairsAutomation\CS\bin\Debug\net8.0-windows\StairsAutomation.dll
Revit.SDK.Samples.StairsAutomation.CS.Command

Elements
Toposolid API Samples
API samples for toposolid related features.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Toposolid\CS\bin\Debug\net8.0-windows\Toposolid.dll
Revit.SDK.Samples.Toposolid.CS.Command

Elements
Winder Stairs
API Sketched Winder Stairs
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\WinderStairs\CS\bin\Debug\net8.0-windows\WinderStairs.dll
Revit.SDK.Samples.WinderStairs.CS.Command

Elements, Geometry
Shaft Hole Puncher
Create shaft opening or create opening on wall, floor or beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ShaftHolePuncher\CS\bin\Debug\net8.0-windows\ShaftHolePuncher.dll
Revit.SDK.Samples.ShaftHolePuncher.CS.Command

Elements, Geometry
SlabShapeEditing
Create vertex and crease on slab to edit it's shape.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SlabShapeEditing\CS\bin\Debug\net8.0-windows\SlabShapeEditing.dll
Revit.SDK.Samples.SlabShapeEditing.CS.Command

Elements, Geometry, Structure, UI
Create Analytical Member
Create Analytical Member
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateAnalyticalMember

Elements, Geometry, Structure, UI
Create Analytical Panel
Create Analytical Panel
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateAnalyticalPanel

Elements, Geometry, Structure, UI
Add relation
Add relation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.AddRelation

Elements, Geometry, Structure, UI
Update relation
Update relation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.UpdateRelation

Elements, Geometry, Structure, UI
Break relation
Break relation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.BreakRelation

Elements, Geometry, Structure, UI
Modify Panel Contour
Modify Panel Contour
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.ModifyPanelContour

Elements, Geometry, Structure, UI
Move an Analytical Panel using ElementTransformUtils
Move an Analytical Panel using ElementTransformUtils while keeping connectivity
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalPanelUsingElementTransformUtils

Elements, Geometry, Structure, UI
Move an Analytical Panel using SketchEditScope
Move an Analytical Panel using SketchEditScope loosing connectivity
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalPanelUsingSketchEditScope

Elements, Geometry, Structure, UI
Move an Analytical Member using UsingElementTransformUtils
Move an Analytical Member using UsingElementTransformUtils keeping connectivity
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalMemberUsingElementTransformUtils

Elements, Geometry, Structure, UI
Move an Analytical Member using SketchEditScope
Move an Analytical Member using SetCurve loosing connectivity
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalMemberUsingSetCurve

Elements, Geometry, Structure, UI
Move an Analytical Node using ElementTransformUtils
Move an Analytical Node using ElementTransformUtils keeping connectivity
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MoveAnalyticalNodeUsingElementTransformUtils

Elements, Geometry, Structure, UI
Flip Analytical Member
Flips an Analytical Member
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.FlipAnalyticalMember

Elements, Geometry, Structure, UI
Align Analytical Element Local Coordinate System
Align Analytical Element Local Coordinate System
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.AnalyticalElementLocalCoordinateSystem

Elements, Geometry, Structure, UI
Check Connection Status
Check Connection Status
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.AnalyticalNodeConnStatus

Elements, Geometry, Structure, UI
Member Forces Analytical Member
Member Forces Analytical Member
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.MemberForcesAnalyticalMember

Elements, Geometry, Structure, UI
Release Conditions Analytical Member
Release Conditions Analytical Member
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.ReleaseConditionsAnalyticalMember

Elements, Geometry, Structure, UI
Sets OuterContour for Analytical Panels
Sets OuterContour for Analytical Panels
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.SetOuterContourForPanels

Elements, Geometry, Structure, UI
Create Analytical Curved Panel
Create Analytical Curved Panel
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ContextualAnalyticalModel\CS\bin\Debug\net8.0-windows\ContextualAnalyticalModel.dll
ContextualAnalyticalModel.CreateAnalyticalCurvedPanel

Elements, Parameters
Move Linear
Move a linear element, such as a structural beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MoveLinear\CS\bin\Debug\net8.0-windows\MoveLinear.dll
Revit.SDK.Samples.MoveLinear.CS.Command

Elements, Parameters
Slab Properties (CS)
Display slab properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SlabProperties\CS\bin\x64\Debug\net8.0-windows\SlabProperties.dll
Revit.SDK.Samples.SlabProperties.CS.Command

Elements, Parameters
Span Direction
Display slab properties (span direction and span direction symbols).
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SpanDirection\CS\bin\Debug\net8.0-windows\SpanDirection.dll
Revit.SDK.Samples.SpanDirection.CS.Command

Families
Create Air Handler
Create one air handler and add connectors.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\CreateAirHandler\CS\bin\Debug\net8.0-windows\CreateAirHandler.dll
Revit.SDK.Samples.CreateAirHandler.CS.Command

Families
Create Truss
Create truss in truss family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\CreateTruss\CS\bin\Debug\net8.0-windows\CreateTruss.dll
Revit.SDK.Samples.CreateTruss.CS.Command

Families
GenericModelCreation
The sample show how to create Generic Model family at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\GenericModelCreation\CS\bin\Debug\net8.0-windows\GenericModelCreation.dll
Revit.SDK.Samples.GenericModelCreation.CS.Command

Families
TypeRegeneration
The command check every type regeneration without any error
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\TypeRegeneration\CS\bin\Debug\net8.0-windows\TypeRegeneration.dll
Revit.SDK.Samples.TypeRegeneration.CS.Command

Families
ValidateParameters
This command will validate if every type has valid values for certain parameter
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\ValidateParameters\CS\bin\Debug\net8.0-windows\ValidateParameters.dll
Revit.SDK.Samples.ValidateParameters.CS.Command

Families
WindowWizard
This command is to create window family via wizard
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\WindowWizard\CS\bin\Debug\net8.0-windows\WindowWizard.dll
Revit.SDK.Samples.WindowWizard.CS.Command

Families
In-Place Members
Display In-Place Member's Properties and AnalyticalModel.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\InPlaceMembers\CS\bin\Debug\net8.0-windows\InPlaceMembers.dll
Revit.SDK.Samples.InPlaceMembers.CS.Command

Families
DividedSurface by intersects
Customize DividedSurface with intersection elements
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\DividedSurfaceByIntersects\CS\bin\Debug\net8.0-windows\DividedSurfaceByIntersects.dll
Revit.SDK.Samples.DividedSurfaceByIntersects.CS.Command

Families
New Extrusion Form
The sample show how to create extrusion form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\net8.0-windows\NewForm.dll
Revit.SDK.Samples.NewForm.CS.MakeExtrusionForm

Families
New Revolve Form
The sample show how to create revolve form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\net8.0-windows\NewForm.dll
Revit.SDK.Samples.NewForm.CS.MakeRevolveForm

Families
New Loft Form
The sample show how to create loft form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\net8.0-windows\NewForm.dll
Revit.SDK.Samples.NewForm.CS.MakeLoftForm

Families
New Swept Blend Form
The sample show how to create swept blend form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\net8.0-windows\NewForm.dll
Revit.SDK.Samples.NewForm.CS.MakeSweptBlendForm

Families
New Cap Form
The sample show how to create cap form at family document.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\NewForm\CS\bin\Debug\net8.0-windows\NewForm.dll
Revit.SDK.Samples.NewForm.CS.MakeCapForm

Families
Place FamilyInstance by face
Create family instance on face.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PlaceFamilyInstanceByFace\CS\bin\Debug\net8.0-windows\PlaceFamilyInstanceByFace.dll
Revit.SDK.Samples.PlaceFamilyInstanceByFace.CS.Command

Families
Type Selector
Retrieve all the types of the selected element, such as a wall and allow the selected element's type to be changed.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TypeSelector\VB.NET\bin\x64\Debug\net8.0-windows\TypeSelector.dll
Revit.SDK.Samples.TypeSelector.VB.NET.Command

Families, MEP
Create Ductwork Stiffener
Create Ductwork Stiffener
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateDuctworkStiffener\CS\bin\Debug\net8.0-windows\CreateDuctworkStiffener.dll
Revit.SDK.Samples.CreateDuctworkStiffener.CS.Command

Families, Parameters
AddParameterToFamily
Sample to show how to automatically add a large set of parameters to a family.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\AutoParameter\CS\bin\Debug\net8.0-windows\AutoParameter.dll
Revit.SDK.Samples.AutoParameter.CS.AddParameterToFamily

Families, Parameters
AddParameterToFamilies
Sample to show how to automatically add a large set of parameters to multiple family files.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\AutoParameter\CS\bin\Debug\net8.0-windows\AutoParameter.dll
Revit.SDK.Samples.AutoParameter.CS.AddParameterToFamilies

Families, Parameters
Command
Command
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyParametersOrder\CS\bin\Debug\net8.0-windows\FamilyParametersOrder.dll
Revit.SDK.Samples.FamilyParametersOrder.CS.Command

Geometry
Multithreaded Calculation
Multithreaded Calculation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AnalysisVisualizationFramework\MultithreadedCalculation\CS\bin\Debug\net8.0-windows\MultithreadedCalculation.dll
Revit.SDK.Samples.MultithreadedCalculation.CS.MultithreadedCalculation

Geometry
Gradient Results On Surface
Gradient Results On Surface
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AnalysisVisualizationFramework\SpatialFieldGradient\CS\bin\Debug\net8.0-windows\SpatialFieldGradient.dll
Revit.SDK.Samples.AnalysisVisualizationFramework.CS.SpatialFieldGradient

Geometry
South Facing Walls Without ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\net8.0-windows\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWallsWithoutProjectLocation

Geometry
South Facing Walls With ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\net8.0-windows\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWallsWithProjectLocation

Geometry
South Facing Windows Without ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\net8.0-windows\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWindowsWithoutProjectLocation

Geometry
South Facing Windows With ProjectLocation
""
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DirectionCalculation\CS\bin\Debug\net8.0-windows\DirectionCalculation.dll
Revit.Samples.DirectionCalculation.FindSouthFacingWindowsWithProjectLocation

Geometry
Auto Join
Automatically join geometry of combinable elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FamilyCreation\AutoJoin\CS\bin\Debug\net8.0-windows\AutoJoin.dll
Revit.SDK.Samples.AutoJoin.CS.Command

Geometry
Find Columns Embedded In Walls
Find Columns Embedded In Walls
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FindReferencesByDirection\FindColumns\CS\bin\Debug\net8.0-windows\FindColumns.dll
Revit.SDK.Samples.FindColumns.CS.Command

Geometry
Measure Height of Skylight
Measure Height of Skylight
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FindReferencesByDirection\MeasureHeight\CS\bin\Debug\net8.0-windows\MeasureHeight.dll
Revit.SDK.Samples.MeasureHeight.CS.Command

Geometry
RayTraceBounce
Find intersection between ray and face and create connecting lines.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FindReferencesByDirection\RaytraceBounce\CS\bin\Debug\net8.0-windows\RayTraceBounce.dll
Revit.SDK.Samples.RayTraceBounce.CS.Command

Geometry
ComputedSymbolGeometry
Demonstrates how to get the computed symbol geometry.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\ComputedSymbolGeometry\CS\bin\Debug\net8.0-windows\ComputedSymbolGeometry.dll
Revit.SDK.Samples.ComputedSymbolGeometry.CS.Command

Geometry
GeometryCreation_BooleanOperation
GeometryCreation and BooleanOperation
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\GeometryCreation_BooleanOperation\CS\bin\Debug\net8.0-windows\GeometryCreation_BooleanOperation.dll
Revit.SDK.Samples.GeometryCreation_BooleanOperation.CS.Command

Geometry
Proximity Detection and Wall Join Control
The usage of  ElementIntersectsSolidFilter,ElementIntersectsElementFilter and WallUtils
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GeometryAPI\ProximityDetection_WallJoinControl\CS\bin\Debug\net8.0-windows\ProximityDetection_WallJoinControl.dll
Revit.SDK.Samples.ProximityDetection_WallJoinControl.CS.Command

Geometry
Compute distance to panels
Compute the distance from a selected object to all panels and store in a panel instance parameter
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\DistanceToPanels\CS\bin\Debug\net8.0-windows\DistanceToPanels.dll
Revit.SDK.Samples.DistanceToPanels.CS.SetDistanceParam

Geometry
Manipulate form
Show how to manipulate edges and profiles of form
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\ManipulateForm\CS\bin\Debug\net8.0-windows\ManipulateForm.dll
Revit.SDK.Samples.ManipulateForm.CS.Command

Geometry
Measure Panel Area
Measure curtain panels on divided surfaces and identify panels beyond a user-specified range
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\MeasurePanelArea\CS\bin\Debug\net8.0-windows\MeasurePanelArea.dll
Revit.SDK.Samples.MeasurePanelArea.CS.MeasurePanelArea

Geometry
Compute the length and angle of edges
Measure curtain panels on divided surfaces, store the length and angle data to parameters
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PanelEdgeLengthAngle\CS\bin\Debug\net8.0-windows\PanelEdgeLengthAngle.dll
Revit.SDK.Samples.PanelEdgeLengthAngle.CS.SetLengthAngleParams

Geometry
Points Along Parabola
Points Along Parabola
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\net8.0-windows\PointCurveCreation.dll
Revit.SDK.Samples.PointCurveCreation.CS.PointsParabola

Geometry
Points On Curve
Points On Curve
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\net8.0-windows\PointCurveCreation.dll
Revit.SDK.Samples.PointCurveCreation.CS.PointsOnCurve

Geometry
Points From Text File
Points From Text File
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\net8.0-windows\PointCurveCreation.dll
Revit.SDK.Samples.PointCurveCreation.CS.PointsFromTextFile

Geometry
Curve - Sine
Curve - Sine
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\net8.0-windows\PointCurveCreation.dll
Revit.SDK.Samples.PointCurveCreation.CS.SineCurve

Geometry
Curve - Catenary
Curve - Catenary
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\net8.0-windows\PointCurveCreation.dll
Revit.SDK.Samples.PointCurveCreation.CS.CatenaryCurve

Geometry
Surface - Cyclic
Surface - Cyclic
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\PointCurveCreation\CS\bin\Debug\net8.0-windows\PointCurveCreation.dll
Revit.SDK.Samples.PointCurveCreation.CS.CyclicSurface

Geometry
Material Quantities
Material Quantities
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MaterialQuantities\CS\bin\Debug\net8.0-windows\MaterialQuantities.dll
Revit.Samples.MaterialQuantities.Command

Geometry
AddPredefinedInstance - Point Cloud Engine
Add predefined instance
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\net8.0-windows\PointCloudEngine.dll
Revit.SDK.Samples.CS.PointCloudEngine.AddPredefinedInstanceCommand

Geometry
Add randomized instance - Point Cloud Engine
Add randomized instance
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\net8.0-windows\PointCloudEngine.dll
Revit.SDK.Samples.CS.PointCloudEngine.AddRandomizedInstanceCommand

Geometry
Add randomized instance at transform - Point Cloud Engine
Add randomized instance at transform
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\net8.0-windows\PointCloudEngine.dll
Revit.SDK.Samples.CS.PointCloudEngine.AddTransformedInstanceCommand

Geometry
Serialize point cloud (utility) - Point Cloud Engine
Serialize point cloud (utility)
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PointCloudEngine\CS\bin\Debug\net8.0-windows\PointCloudEngine.dll
Revit.SDK.Samples.CS.PointCloudEngine.SerializePredefinedPointCloud

Geometry
SolidSolidCut-Cut
"Let the sphere cut the cube"
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SolidSolidCut\CS\bin\Debug\net8.0-windows\SolidSolidCut.dll
Revit.SDK.Samples.SolidSolidCut.CS.Cut

Geometry
SolidSolidCut-Uncut
"Remove the cutting relationship between the sphere and the cube"
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SolidSolidCut\CS\bin\Debug\net8.0-windows\SolidSolidCut.dll
Revit.SDK.Samples.SolidSolidCut.CS.Uncut

Geometry
Analytical Viewer
Display analytical model of one or more selected elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\AnalyticalViewer\VB.NET\bin\x64\Debug\net8.0-windows\AnalyticalViewer.dll
Revit.SDK.Samples.AnalyticalViewer.VB.NET.AnalyticalViewer

Geometry
Element Viewer
Display wireframe model of one or more selected elements.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\ElementViewer\VB.NET\bin\x64\Debug\net8.0-windows\ElementViewer.dll
Revit.SDK.Samples.ElementViewer.VB.NET.ElementViewer

Geometry
Revit Viewer
View geometry information.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\RevitViewer\VB.NET\bin\x64\Debug\net8.0-windows\RevitViewer.dll
Revit.SDK.Samples.RevitViewer.VB.NET.RevitViewer

Geometry
Room Viewer
Wireframe viewer for the selected room.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Viewers\RoomViewer\VB.NET\bin\x64\Debug\net8.0-windows\RoomViewer.dll
Revit.SDK.Samples.RoomViewer.VB.NET.RoomViewer

Geometry, Structure
NewPathReinforcement
Create PathReinforcement on wall or slab.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewPathReinforcement\CS\bin\Debug\net8.0-windows\NewPathReinforcement.dll
Revit.SDK.Samples.NewPathReinforcement.CS.Command

Geometry, Structure
Truss
Create truss, edit profile and truss member of new created truss.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Truss\CS\bin\Debug\net8.0-windows\Truss.dll
Revit.SDK.Samples.Truss.CS.Command

Massing
Set Parameter Values From Image Data
Set Parameter Values From Image Data
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Massing\ParameterValuesFromImage\CS\bin\Debug\net8.0-windows\ParameterValuesFromImage.dll
Revit.SDK.Samples.ParameterValuesFromImage.CS.SetParameterValueWithImageData

Materials
Edit appearance asset properties via a small control dialog
This sample demonstrates basic usage of the AppearanceAssetEditScope and AssetProperty classes to change the value of an asset property in a given material. 
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AppearanceAssetEditing\CS\bin\Debug\net8.0-windows\AppearanceAssetEditing.dll
Revit.SDK.Samples.AppearanceAssetEditing.CS.Command

Materials
Material Properties (CS)
Get the material physical properties of the selected beam, column or brace.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MaterialProperties\CS\bin\Debug\net8.0-windows\MaterialProperties.dll
Revit.SDK.Samples.MaterialProperties.CS.MaterialProperties

Materials, Parameters
Physical Properties
Dump Material Physical Parameters.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PhysicalProp\CS\bin\Debug\net8.0-windows\PhysicalProp.dll
Revit.SDK.Samples.PhysicalProp.CS.DumpMaterialPhysicalParameters

MEP
AutoRoute
Route ducts and fittings.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AutoRoute\CS\bin\Debug\net8.0-windows\AutoRoute.dll
Revit.SDK.Samples.AutoRoute.CS.Command

MEP
AvoidObstruction
Resolve the obstructions of pipe with pipe, pipe with beam and pipe with duct.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AvoidObstruction\CS\bin\Debug\net8.0-windows\AvoidObstruction.dll
Revit.SDK.Samples.AvoidObstruction.CS.Command

MEP
Fabrication Part Layout
Fabrication Part Layout Sample
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.FabricationPartLayout

MEP
Optimize Straights
Optimize Straights
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.OptimizeStraights

MEP
Stretch and Fit
Stretch and fit
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.StretchAndFit

MEP
Convert To Fabrication
Convert Design Elements To Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.ConvertToFabrication

MEP
Buttons and Palette Exclusions
Exclude Fabrication Service Buttons and Palettes for Routing Operations
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.ButtonPaletteExclusions

MEP
Ancillaries
Discover the Ancillaries Associated with a Fabrication Part
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.Ancillaries

MEP
Get Custom Data
Discover the Custom data Associated with a Fabrication Config and Part
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.GetCustomData

MEP
Set Custom Data
Set Custom data Associated with a Fabrication Config to a Selected Part
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.SetCustomData

MEP
Export to PCF
Exports fabrication parts to a PCF file
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.ExportToPCF

MEP
Export Part Geometry
Exports fabrication part geometry to a CSV file
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.FabPartGeometry

MEP
Display Part Info
Displays fabrication part information
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.PartInfo

MEP
Detach Hanger Rods
Detaches hanger rods from their structural host
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.DetachRods

MEP
Double Rod Lengths
Doubles the length of the picked hanger rods
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.DoubleRodLength

MEP
Halve Rod Lengths
Halves the length of the picked hanger rods
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.HalveRodLength

MEP
Increase Rod Structure Extension
Increase the length of the rod as an extension from its hosted structure (by 1ft)
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.IncreaseRodStructureExtension

MEP
Decrease Rod Structure Extension
Decrease the length of the rod as an extension from its hosted structure (by 1ft)
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.DecreaseRodStructureExtension

MEP
Part Renumber
Renumbers a selection of fabrication parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.PartRenumber

MEP
Split Straight
Splits a fabrication part straight into two equal pieces
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.SplitStraight

MEP
Load and Place Next Item File
Reloads the fabrication configuration and then iterates the item folders and finds the next unloaded item file and lets a user place it in the model
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.LoadAndPlaceNextItemFile

MEP
Unload Unused Item Files
Unloads item files that are loaded but are not used in the model
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.UnloadUnusedItemFiles

MEP
Export to MAJ
Export Fabrication Parts to a fabrication job (MAJ) file
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.ExportToMAJ

MEP
Change Service
Change the service of a selection of Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.ChangeService

MEP
Change Size
Change the size of a selection of Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.ChangeSize

MEP
Apply Change
Apply change to the service and the size of a selection of Fabrication Parts
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.ApplyChange

MEP
Flip Part
Flips a Fabrication Part to the opposite direction
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FabricationPartLayout\CS\bin\Debug\net8.0-windows\FabricationPartLayout.dll
Revit.SDK.Samples.FabricationPartLayout.CS.FlipPart

MEP
Pressure Loss Report
Report the pressure loss for the network flow calculation.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NetworkPressureLossReport\CS\bin\x64\Debug\net8.0-windows\NetworkPressureLossReport.dll
Revit.SDK.Samples.NetworkPressureLossReport.Command

MEP
Power Circuit
Operate power circuits.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PowerCircuit\CS\bin\Debug\net8.0-windows\PowerCircuit.dll
Revit.SDK.Samples.PowerCircuit.CS.Command

MEP
RoutingPreferenceTools.Analyzer
RoutingPreferenceTools.Analyzer
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoutingPreferenceTools\CS\bin\x64\Debug\net8.0-windows\RoutingPreferenceTools.dll
Revit.SDK.Samples.RoutingPreferenceTools.CS.Command

MEP
RoutingPreferenceTools.Builder.CommandReadPreferences
RoutingPreferenceTools.Builder.CommandReadPreferences
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoutingPreferenceTools\CS\bin\x64\Debug\net8.0-windows\RoutingPreferenceTools.dll
Revit.SDK.Samples.RoutingPreferenceTools.CS.CommandReadPreferences

MEP
RoutingPreferenceTools.Builder.CommandWritePreferences
RoutingPreferenceTools.Builder.CommandWritePreferences
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoutingPreferenceTools\CS\bin\x64\Debug\net8.0-windows\RoutingPreferenceTools.dll
Revit.SDK.Samples.RoutingPreferenceTools.CS.CommandWritePreferences

MEP
TraverseSystem
Traverse a mechanical or piping system in the direction of flow
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TraverseSystem\CS\bin\Debug\net8.0-windows\TraverseSystem.dll
Revit.SDK.Samples.TraverseSystem.CS.Command

Parameters
Beam and slab parameter
Add a new GUID parameter to beam and slab, and use the GUID value to find the right element.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\BeamAndSlabNewParameter\CS\bin\Debug\net8.0-windows\BeamAndSlabNewParameter.dll
Revit.SDK.Samples.BeamAndSlabNewParameter.CS.Command

Parameters
Browse Parameter Bindings
Browse all the shared parameters bindings used in this project.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\BrowseBindings\VB.NET\bin\x64\Debug\net8.0-windows\BrowseBindings.dll
Revit.SDK.Samples.BrowseBindings.VB.NET.Command

Parameters
CreateShared - Create Shared Parameter
Create a new shared parameter and assign it to wall categories.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateShared\VB.NET\bin\x64\Debug\net8.0-windows\CreateShared.dll
Revit.SDK.Samples.CreateShared.VB.NET.Command1

Parameters
CreateShared - Set Shared Parameter
Set the shared parameter.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateShared\VB.NET\bin\x64\Debug\net8.0-windows\CreateShared.dll
Revit.SDK.Samples.CreateShared.VB.NET.Command2

Parameters
Get Deck Properties
Get deck layer properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DeckProperties\CS\bin\Debug\net8.0-windows\DeckProperties.dll
Revit.SDK.Samples.DeckProperties.CS.Command

Parameters
FireRating - Apply Parameter
Add a new shared parameter to Revit and apply it to all doors.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FireRating\VB.NET\bin\x64\Debug\net8.0-windows\FireRating.dll
Revit.SDK.Samples.FireRating.VB.NET.ApplyParameter

Parameters
FireRating - Export to Excel
Export fire rating values to an Excel file.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FireRating\VB.NET\bin\x64\Debug\net8.0-windows\FireRating.dll
Revit.SDK.Samples.FireRating.VB.NET.ExportFireRating

Parameters
FireRating - Import from Excel
Import fire rating values from the Excel file and apply them to doors.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FireRating\VB.NET\bin\x64\Debug\net8.0-windows\FireRating.dll
Revit.SDK.Samples.FireRating.VB.NET.ImportFireRating

Parameters
Create shared parameters
Create a visible and an invisible parameter.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\InvisibleParam\CS\bin\Debug\net8.0-windows\InvisibleParam.dll
Revit.SDK.Samples.InvisibleParam.CS.Command

Parameters
Element Parameters
Show the property information of selected element.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ParameterUtils\CS\bin\Debug\net8.0-windows\ParameterUtils.dll
Revit.SDK.Samples.ParameterUtils.CS.Command

Parameters
ReadonlySharedParameters1
ReadonlySharedParameters1
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ReadonlySharedParameters\CS\bin\Debug\net8.0-windows\ReadonlySharedParameters.dll
Revit.SDK.Samples.ReadonlySharedParameters.CS.SetReadonlyCost1

Parameters
ReadonlySharedParameters2
ReadonlySharedParameters2
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ReadonlySharedParameters\CS\bin\Debug\net8.0-windows\ReadonlySharedParameters.dll
Revit.SDK.Samples.ReadonlySharedParameters.CS.SetReadonlyCost2

Parameters
Test Floor Thickness
Show how to retrieve and modify floor thickness.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TestFloorThickness\VB.NET\bin\x64\Debug\net8.0-windows\TestFloorThickness.dll
Revit.SDK.Samples.TestFloorThickness.VB.NET.Command

Parameters
Test Wall Thickness
Show how to retrieve and modify wall thickness.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\TestWallThickness\VB.NET\bin\x64\Debug\net8.0-windows\TestWallThickness.dll
Revit.SDK.Samples.TestWallThickness.VB.NET.Command

Parameters, Structure
Create beams, columns and braces (CS)
Create beams, columns and braces.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateBeamsColumnsBraces\CS\bin\Debug\net8.0-windows\CreateBeamsColumnsBraces.dll
Revit.SDK.Samples.CreateBeamsColumnsBraces.CS.Command

Parameters, Views
Create and configure new view template
Demonstrates the process of creating a new view template from a regular view.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ViewTemplateCreation\CS\bin\Debug\net8.0-windows\ViewTemplateCreation.dll
Revit.SDK.Samples.ViewTemplateCreation.CS.Command

Rooms/Spaces
Create zone and space
Create space/zone elements and edit zone in Revit MEP.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AddSpaceAndZone\CS\bin\Debug\net8.0-windows\AddSpaceAndZone.dll
Revit.SDK.Samples.AddSpaceAndZone.CS.Command

Rooms/Spaces
Customize door opening expression
Customize door opening expression based on geometry and your country standard.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DoorSwing\CS\bin\Debug\net8.0-windows\DoorSwing.dll
Revit.SDK.Samples.DoorSwing.CS.InitializeCommand

Rooms/Spaces
Update Door Properties
Update Door Properties according to geometries.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DoorSwing\CS\bin\Debug\net8.0-windows\DoorSwing.dll
Revit.SDK.Samples.DoorSwing.CS.UpdateParamsCommand

Rooms/Spaces
Update Door Geometries
Update door geometry according to From/To room property.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\DoorSwing\CS\bin\Debug\net8.0-windows\DoorSwing.dll
Revit.SDK.Samples.DoorSwing.CS.UpdateGeometryCommand

Rooms/Spaces
Roofs Rooms (CS)
Demonstrates how to check whether Room(Space) has bounding Roof.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoofsRooms\CS\bin\Debug\net8.0-windows\RoofsRooms.dll
Revit.SDK.Samples.RoofsRooms.CS.Command

Rooms/Spaces
Rooms
Get and set room information (Number, Tag, Area).
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Rooms\CS\bin\Debug\net8.0-windows\Rooms.dll
Revit.SDK.Samples.Rooms.CS.Command

Rooms/Spaces
Room Schedule
Room Schedule.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RoomSchedule\CS\bin\Debug\net8.0-windows\RoomSchedule.dll
Revit.SDK.Samples.RoomSchedule.Command

Selection
Pick for Deletion
This command is to pick element and delete.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\net8.0-windows\Selections.dll
Revit.SDK.Samples.Selections.CS.PickforDeletion

Selection
Place At Point On Wall Face
This command is to pick a point on wall face and place a window.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\net8.0-windows\Selections.dll
Revit.SDK.Samples.Selections.CS.PlaceAtPointOnWallFace

Selection
Place At Picked Face Work plane
This command is to pick a face, set work plane, then pick a point to create a circle.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\net8.0-windows\Selections.dll
Revit.SDK.Samples.Selections.CS.PlaceAtPickedFaceWorkplane

Selection
Selection Dialog
This command is to pick a element and a point from dialog.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Selections\CS\bin\Debug\net8.0-windows\Selections.dll
Revit.SDK.Samples.Selections.CS.SelectionDialog

Structure
AreaReinCurve
Turn off all layers but one. You get some parallel bars. Remove the hooks from one boundary curve so that the bars have hooks only at the other end.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AreaReinCurve\CS\bin\Debug\net8.0-windows\AreaReinCurve.dll
Revit.SDK.Samples.AreaReinCurve.CS.Command

Structure
AreaReinParameters
Show parameters of selected AreaReinforcement and allow user to modify
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AreaReinParameters\CS\bin\Debug\net8.0-windows\AreaReinParameters.dll
Revit.SDK.Samples.AreaReinParameters.CS.Command

Structure
RebarParameters
Show all parameters of selected Rebar
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AreaReinParameters\CS\bin\Debug\net8.0-windows\AreaReinParameters.dll
Revit.SDK.Samples.AreaReinParameters.CS.RebarParas

Structure
Boundary Conditions
Display the BoundaryConditions' parameters or create a new BoundaryConditions instance.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\BoundaryConditions\CS\bin\Debug\net8.0-windows\BoundaryConditions.dll
Revit.SDK.Samples.BoundaryConditions.CS.Command

Structure
Create Beam System
Create beam system according to the profile made of selected beams.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateBeamSystem\CS\bin\Debug\net8.0-windows\CreateBeamSystem.dll
Revit.SDK.Samples.CreateBeamSystem.CS.Command

Structure
Create Complex Area Reinforcement
Create complex AreaReinforcement on selected slab.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateComplexAreaRein\CS\bin\Debug\net8.0-windows\CreateComplexAreaRein.dll
Revit.SDK.Samples.CreateComplexAreaRein.CS.Command

Structure
Create simple area reinforcement
Create simple AreaReinforcement on selected wall or floor.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateSimpleAreaRein\CS\bin\Debug\net8.0-windows\CreateSimpleAreaRein.dll
Revit.SDK.Samples.CreateSimpleAreaRein.CS.Command

Structure
Create wall in beam profile
Create a profiled wall using the outline generated by a selection of beams defining a vertical profile.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateWallinBeamProfile\CS\bin\Debug\net8.0-windows\CreateWallinBeamProfile.dll
Revit.SDK.Samples.CreateWallinBeamProfile.CS.CreateWallinBeamProfile

Structure
Create walls under beams
Create simple rectangular walls along and under the path of selected beams.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateWallsUnderBeams\CS\bin\Debug\net8.0-windows\CreateWallsUnderBeams.dll
Revit.SDK.Samples.CreateWallsUnderBeams.CS.CreateWallsUnderBeams

Structure
Create Curved Beam
Create Curved Beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CurvedBeam\CS\bin\Debug\net8.0-windows\CurvedBeam.dll
Revit.SDK.Samples.CurvedBeam.CS.Command

Structure
Frame Builder
Add a new concrete column and beam size.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\FrameBuilder\CS\bin\Debug\net8.0-windows\FrameBuilder.dll
Revit.SDK.Samples.FrameBuilder.CS.Command

Structure
Structural connection basic operations
Shows how to perform basic operations on a structural connection.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\GenericStructuralConnection\CS\bin\Debug\net8.0-windows\GenericStructuralConnection.dll
Revit.SDK.Samples.GenericStructuralConnection.CS.Command

Structure
Loads
Show how to use load case, nature, usage and combination.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Loads\CS\bin\Debug\net8.0-windows\Loads.dll
Revit.SDK.Samples.Loads.CS.Loads

Structure
Multiplanar Rebar
Demonstrates how to create multiplanar rebar.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\MultiplanarRebar\CS\bin\Debug\net8.0-windows\MultiplanarRebar.dll
Revit.SDK.Samples.MultiplanarRebar.CS.Command

Structure
NewRebar
Create a rebar on the selected concrete rectangular column or beam.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\NewRebar\CS\bin\Debug\net8.0-windows\NewRebar.dll
Revit.SDK.Samples.NewRebar.CS.Command

Structure
PathReinforcement
Display path reinforcement properties.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\PathReinforcement\CS\bin\Debug\net8.0-windows\PathReinforcement.dll
Revit.SDK.Samples.PathReinforcement.CS.Command

Structure
RebarContainerAnyShapeType
Create Rebar Container in a selected concrete element (beam or column) that does not have any reinforcement.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RebarContainerAnyShapeType\CS\bin\Debug\net8.0-windows\RebarContainerAnyShapeType.dll
Revit.SDK.Samples.RebarContainerAnyShapeType.CS.Command

Structure
Add Parameters
External command to add shared parameters to Rebar
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RebarFreeForm\CS\bin\Debug\net8.0-windows\RebarFreeForm.dll
Revit.SDK.Samples.RebarFreeForm.CS.AddSharedParams

Structure
Create Rebar Free Form
External command to create a Rebar FreeForm element and external application to implement the custom server used to regenerate the rebar geometry based on constraints
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\RebarFreeForm\CS\bin\Debug\net8.0-windows\RebarFreeForm.dll
Revit.SDK.Samples.RebarFreeForm.CS.Command

Structure
Reinforcement
Create bar set in a selected concrete element (beam or column) that does not have any reinforcement.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\Reinforcement\CS\bin\Debug\net8.0-windows\Reinforcement.dll
Revit.SDK.Samples.Reinforcement.CS.Command

Structure
Add elements to connection
Add elements to existing structural connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.AddElementsToConnection.CS.Command

Structure
Add elements to custom connection
Add elements to existing custom connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.AddElementsToCustomConnection.CS.Command

Structure
Add ranges of applicability to a connection type
Add ranges of applicability to a connection type
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.AddRangesToConnectionType.CS.Command

Structure
Create anchor pattern
Create anchor pattern
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateAnchorPattern.CS.Command

Structure
Create bolt pattern
Create bolt pattern
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateBoltPattern.CS.Command

Structure
Create contour cut
Create contour cut
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateContourCut.CS.Command

Structure
Create cope skewed
Create cope skewed
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateCopeSkewed.CS.Command

Structure
Create corner cut
Create corner cut
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateCornerCut.CS.Command

Structure
Create plate
Create plate
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreatePlate.CS.Command

Structure
Create plate hole
Create plate hole
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreatePlateHole.CS.Command

Structure
Create shear stud pattern
Create shear stud pattern
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateShearStudPattern.CS.Command

Structure
Create shortening
Create shortening
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateShortening.CS.Command

Structure
Create weld point
Create weld point
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.CreateWeldPoint.CS.Command

Structure
Delete connection
Delete connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.DeleteConnection.CS.Command

Structure
Remove elements from structural connection
Remove elements from structural connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.RemoveElementsFromConnection.CS.Command

Structure
Remove subelements from custom connection
Remove subelements from custom connection
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.RemoveSubelementsFromCustomConnection.CS.Command

Structure
Print connection detailed parameters
Print connection detailed parameters
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.UpdateConnectionDetailedParameters.CS.Command

Structure
Fabrication transaction and background calculation
Shows how to handle "Background calculation in progress" exception when trying to start fabrication transaction
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SampleCommandsSteelElements\CS\bin\Debug\net8.0-windows\SampleCommandsSteelElements.dll
Revit.SDK.Samples.SampleCommandsSteelElements.BackgroundCalculation.CS.Command

Structure
StructSample - Frame Wall
Add columns to the selected walls.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\StructSample\CS\bin\Debug\net8.0-windows\StructSample.dll
Revit.SDK.Samples.StructSample.CS.Command

Structure
Structural Layer Function (CS)
For the selected floor, display the function of each structural layer from outside to inside in a dialog box.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\StructuralLayerFunction\CS\bin\Debug\net8.0-windows\StructuralLayerFunction.dll
Revit.SDK.Samples.StructuralLayerFunction.CS.Command

View Transforms
Sheet To 3D View
Generate a perspective View3D with its camera at a click on a viewport on a sheet
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\SheetToView3D\CS\bin\Debug\net8.0-windows\SheetToView3D.dll
Revit.SDK.Samples.SheetToView3D.CS.Command

Views
All Views
Generate a new sheet for user selected views
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\AllViews\CS\bin\Debug\net8.0-windows\AllViews.dll
Revit.SDK.Samples.AllViews.CS.Command

Views
Create view section
Create a section view across the mid point of the selected wall, floor or beam
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateViewSection\CS\bin\Debug\net8.0-windows\CreateViewSection.dll
Revit.SDK.Samples.CreateViewSection.CS.Command

Views
Create drafting view
Create a new empty drafting view
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\CreateViewSection\CS\bin\Debug\net8.0-windows\CreateViewSection.dll
Revit.SDK.Samples.CreateViewSection.CS.CreateDraftingView

Views
Object Viewer
Display the selected element in a preview window and generic properties in a grid.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ObjectViewer\CS\bin\Debug\net8.0-windows\ObjectViewer.dll
Revit.SDK.Samples.ObjectViewer.CS.Command

Views
ScheduleAPI
This sample introduces how to create a view schedule and how to show its data on a sheet.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\ScheduleCreation\CS\bin\Debug\net8.0-windows\ScheduleCreation.dll
Revit.SDK.Samples.ScheduleCreation.CS.Command

Views
Visibility Controller
Control element visibility by category.
LargeImage:
Image:
Y:\a\src\rvt\RevitSdkSamples\SDK\Samples\VisibilityControl\CS\bin\Debug\net8.0-windows\VisibilityControl.dll
Revit.SDK.Samples.VisibilityControl.CS.Command

